fo = open('456.txt', 'r+')
print('File name: ', fo.name)
line = fo.readline()
print('Read the first line %s'%(line))
line = fo.readline()
print('Read the second line %s'%(line))
line = fo.readline()
print('Read the third line %s'%(line))
line = fo.readline(3)
print('The string read is: %s'%(line))
fo.close()
